<?php
echo "Presented by: Sarvaiya Ronak"; 
echo "<br>";
$a=25;
$b=25;
echo "Value of A : $a<br>"; 
echo "Value of B : $b<br>"; 
echo "__________________"; 
echo "<br>";
echo "Arithmetic Operators:"; 
echo "<br>";
echo "__________________"; 
echo "<br>";
echo "Addition a+b : ".($a+$b); 
echo "<br>";
echo "Subtraction A-B : ".($a-$b); 
echo "<br>";
echo "Multiplication A*B : ".($a*$b); 
echo "<br>";
echo "Division A/B : ".($a/$b); 
echo "<br>";
echo "Module A%B : ".($a%$b); 
echo "<br>";
echo "__________________";
echo "<br>";
echo "Comparison Operators:"; 
echo "<br>";
echo "__________________"; 
echo "<br>";
echo "Equal to A == B : "; var_dump($a == $b); 
echo "<br>";
echo "Not Equal to A != B : "; var_dump($a != $b);
echo "<br>";
echo "Greater than A > B : "; var_dump($a > $b);
echo "<br>";
echo "Less than to A < B : "; var_dump($a < $b);
echo "<br>";
echo "Greater than equal to A >= B : "; var_dump($a >= $b);
echo "<br>";
echo "Less than equal to A<=B : "; var_dump($a <= $b);
echo "<br>";
echo "________________"; 
echo "<br>";
echo "Logical Operators:"; 
echo "<br>";
echo "________________";
echo "<br>"; if($a==15 and $b==10) echo "AND A && B"; 
echo "<br>"; 
if($a==18 or $b==10) 
echo "OR A || B";
echo "<br>"; 
if($a!==10) echo "OR A!"; 
echo "<br>";
?>
