<?php
echo "Presented by: Sarvaiya Ronak"; 
echo "</br></br>";
$str="Hello Ronak...";
echo "Strlen Function: "; 
echo strlen($str);
echo "</br></br>";
echo "Strtolower Function: "; 
echo strtolower($str);
echo "</br></br>";
echo "Strtoupper Function: "; 
echo strtoupper($str);
echo "</br></br>";
echo "Trim Function: ";
$str="Ronak.."; echo trim($str); 
echo "</br></br>";
echo "RTrim Function: ";
$str="Ronak.. "; echo rtrim($str); 
echo "</br></br>";
echo "LTrim Function: ";
$str=" Ronak.."; echo ltrim($str); 
echo "</br></br>";
echo "Char Function: </br>";
$a=50;
echo chr($a);
$a=0x70; echo "</br>"; 
echo chr($a);
echo "</br></br>";
echo "Comapre Function:</br>"; 
echo strcmp("Ronak","ronak")."</br>";
echo strcmp("Ronak","Ronak")."</br>";
echo strcmp("ronak","Ronak")."</br>"; 
echo "</br></br>";
echo "Reverse Function: "; 
echo strrev("kanoR");
echo "</br></br>";
echo "Position Function:</br>"; 
echo strpos("ronak.....","a");
echo "</br></br>";
echo "Substring Function:</br>";
echo substr("Hello How Are You?",5); 
echo "</br></br>";
echo "Replace Function:</br>";
echo str_replace("pizza","maggi","burger"); 
echo "</br></br>";
echo "Print_r Function:</br>";
$arr=array("red","yellow","white"); 
print_r($arr);
echo "<br/>";
?> 
